### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by huumanoid** [huumanoid/xat-cli#1]
- [ ] Multiple chats
- [ ] Handle service messages
  - [ ] Ban & kick
    - [ ] Handle
    - [ ] Emit
  - [ ] Make
    - [ ] Handle
    - [ ] Emit
  - [ ] Protect
    - [ ] Handle
    - [ ] Emit
  - [ ] Handle limit
- [ ] Account management
  - [x] Import from sol
  - [ ] Create new user
  - [ ] Login to regname
  - [ ] Handy switch between different .sol
- [ ] Intelligent message filters
  - [x] Log screen
  - [x] Private chats
  - [ ] Custom message filtering
  - [ ] Locate&response
  - [x] Lurker viewer
  - [ ] Links (with ability to open in default browser)
  - [ ] Search by keyword (xat search api)
- [ ] Accessibility
  - [ ] In-app help
  - [ ] Docs
  - [ ] Different key flavors
- [ ] History
  - [ ] Persistent history
  - [x] Session history
- [ ] User info
  - [x] Basic
  - [ ] Full except powers
  - [ ] Powers (getAllPowers probably needed)
  - [ ] Openable links
  - [ ] Actions
- [ ] Commands
  - [ ] Extendability
  - [ ] Completion
- [ ] Ignore
- [ ] ixat support
- [ ] Message timestamps
- [ ] Isomorphic layer (for future html5 client)
- [ ] Handle captcha
- [ ] Notifications
  - [x] Sometimes content of tab is just updated (highlight tab)
  - [ ] But sometimes update requires a tab creation. Should we create a tab?
- [ ] Pools
- [ ] SOCKS5
- [ ] Modes
  - [ ] Hidden messages `<m l="1" />`
  - [ ] Autoreconnect
